version: '3.8'

services:
  dev:
    volumes:
      - ./:/app/
    network_mode: "host"
    build:
      dockerfile: Dockerfile
      context: .
    image: ${REGISTRY_URL}/mpd:latest
    tty: true
    stdin_open: true
    privileged: true
    restart: unless-stopped
